export const TAG_CATEGORY_VALUES = [
  'MANAGEMENT',
  'BUSINESS_FINANCIAL',
  'COMPUTER_MATHEMATICAL',
  'ARCHITECTURE_ENGINEERING',
  'SCIENCE',
  'COMMUNITY_SOCIAL_SERVICE',
  'LEGAL',
  'EDUCATION_TRAINING',
  'ARTS_DESIGN_MEDIA',
  'SPORTS_ENTERTAINMENT',
  'HEALTHCARE_PRACTITIONER',
  'HEALTHCARE_SUPPORT',
  'PROTECTIVE_SERVICE',
  'FOOD_SERVICE',
  'BUILDING_GROUNDS_MAINTENANCE',
  'PERSONAL_CARE_SERVICE',
  'SALES',
  'OFFICE_ADMINISTRATIVE',
  'FARMING_FISHING_FORESTRY',
  'CONSTRUCTION',
  'INSTALLATION_MAINTENANCE_REPAIR',
  'PRODUCTION_MANUFACTURING',
  'TRANSPORTATION_MATERIAL_MOVING',
  'MILITARY_SPECIFIC',
  'GIG_ECONOMY',
] as const;

export type TagCategoryValue = (typeof TAG_CATEGORY_VALUES)[number];

const TAG_LABELS: Record<TagCategoryValue, string> = {
  MANAGEMENT: 'Management',
  BUSINESS_FINANCIAL: 'Business & Financial',
  COMPUTER_MATHEMATICAL: 'Computer & Mathematical',
  ARCHITECTURE_ENGINEERING: 'Architecture & Engineering',
  SCIENCE: 'Science',
  COMMUNITY_SOCIAL_SERVICE: 'Community & Social Service',
  LEGAL: 'Legal',
  EDUCATION_TRAINING: 'Education & Training',
  ARTS_DESIGN_MEDIA: 'Arts, Design & Media',
  SPORTS_ENTERTAINMENT: 'Sports & Entertainment',
  HEALTHCARE_PRACTITIONER: 'Healthcare Practitioner',
  HEALTHCARE_SUPPORT: 'Healthcare Support',
  PROTECTIVE_SERVICE: 'Protective Service (Law Enforcement, Fire, Security)',
  FOOD_SERVICE: 'Food Service',
  BUILDING_GROUNDS_MAINTENANCE: 'Building & Grounds Maintenance',
  PERSONAL_CARE_SERVICE: 'Personal Care & Service',
  SALES: 'Sales',
  OFFICE_ADMINISTRATIVE: 'Office & Administrative',
  FARMING_FISHING_FORESTRY: 'Farming, Fishing & Forestry',
  CONSTRUCTION: 'Construction',
  INSTALLATION_MAINTENANCE_REPAIR: 'Installation, Maintenance & Repair',
  PRODUCTION_MANUFACTURING: 'Production & Manufacturing',
  TRANSPORTATION_MATERIAL_MOVING: 'Transportation & Material Moving',
  MILITARY_SPECIFIC: 'Military',
  GIG_ECONOMY: 'Gig Economy (Rideshare, Delivery, Freelance)',
};

export const TAG_OPTIONS = TAG_CATEGORY_VALUES.map((value) => ({ value, label: TAG_LABELS[value] }));
