-- CreateEnum
CREATE TYPE "TagCategory" AS ENUM ('MANAGEMENT', 'BUSINESS_FINANCIAL', 'COMPUTER_MATHEMATICAL', 'ARCHITECTURE_ENGINEERING', 'SCIENCE', 'COMMUNITY_SOCIAL_SERVICE', 'LEGAL', 'EDUCATION_TRAINING', 'ARTS_DESIGN_MEDIA', 'SPORTS_ENTERTAINMENT', 'HEALTHCARE_PRACTITIONER', 'HEALTHCARE_SUPPORT', 'PROTECTIVE_SERVICE', 'FOOD_SERVICE', 'BUILDING_GROUNDS_MAINTENANCE', 'PERSONAL_CARE_SERVICE', 'SALES', 'OFFICE_ADMINISTRATIVE', 'FARMING_FISHING_FORESTRY', 'CONSTRUCTION', 'INSTALLATION_MAINTENANCE_REPAIR', 'PRODUCTION_MANUFACTURING', 'TRANSPORTATION_MATERIAL_MOVING', 'MILITARY_SPECIFIC', 'GIG_ECONOMY');

-- AlterTable
ALTER TABLE "CandidateProfile" ADD COLUMN     "tags" "TagCategory"[] DEFAULT ARRAY[]::"TagCategory"[];

-- AlterTable
ALTER TABLE "JobPosting" ADD COLUMN     "tags" "TagCategory"[] DEFAULT ARRAY[]::"TagCategory"[];
